timetables12={
    "A"=[
    {},
    [None,None,None,None,"PD","Break","Optional","Optional",None,None],
    ["Assembly",None,None,None,None,"Break","Optional",None,None,None],
    [None,None,None,None,None,"Break","Optional","Optional",None,None],
    [None,None,None,None,None,"Break","Optional",None,None,None],
    [None,None,"Optional","Optional","PD","Break",None,None,None,None]
    ]
    "B"=[
    {},
    [None,None,None,None,"PD","Break","Optional","Optional",None,None],
    ["Assembly",None,None,None,None,"Break","Optional",None,None,None],
    [None,None,None,None,None,"Break","Optional","Optional",None,None],
    [None,None,None,None,None,"Break","Optional",None,None,None],
    [None,None,"Optional","Optional","PD","Break",None,None,None,None]
    ]
    "C"=[
    {},
    [None,None,None,None,"PD","Break","Optional","Optional",None,None],
    ["Assembly",None,None,None,None,"Break","Optional",None,None,None],
    [None,None,None,None,None,"Break","Optional","Optional",None,None],
    [None,None,None,None,None,"Break","Optional",None,None,None],
    [None,None,"Optional","Optional","PD","Break",None,None,None,None]
    ]
    "D"=[
    {},
    [None,None,None,None,"PD","Break","Optional","Optional",None,None],
    ["Assembly",None,None,None,None,"Break","Optional",None,None,None],
    [None,None,None,None,None,"Break","Optional","Optional",None,None],
    [None,None,None,None,None,"Break","Optional",None,None,None],
    [None,None,"Optional","Optional","PD","Break",None,None,None,None]
    ]
    "E"=[
    {},
    [None,None,None,None,"PD","Break","Optional","Optional",None,None],
    ["Assembly",None,None,None,None,"Break","Optional",None,None,None],
    [None,None,None,None,None,"Break","Optional","Optional",None,None],
    [None,None,None,None,None,"Break","Optional",None,None,None],
    [None,None,"Optional","Optional","PD","Break",None,None,None,None]
    ]
    "F"=[
    {},
    [None,None,None,None,"PD","Break","Optional","Optional",None,None],
    ["Assembly",None,None,None,None,"Break","Optional",None,None,None],
    [None,None,None,None,None,"Break","Optional","Optional",None,None],
    [None,None,None,None,None,"Break","Optional",None,None,None],
    [None,None,"Optional","Optional","PD","Break",None,None,None,None]
    ]
}