# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(874, 479)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.window = QtWidgets.QFrame(self.centralwidget)
        self.window.setGeometry(QtCore.QRect(-130, -30, 1181, 641))
        font = QtGui.QFont()
        font.setFamily("Constantia")
        font.setPointSize(16)
        self.window.setFont(font)
        self.window.setStyleSheet("QFrame#window{\n"
"background-color:qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:1, stop:0 rgba(255, 255, 255, 255), stop:0.00498339 rgba(74, 113, 255, 255), stop:1 rgba(255, 255, 255, 255))\n"
";}")
        self.window.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.window.setFrameShadow(QtWidgets.QFrame.Raised)
        self.window.setObjectName("window")
        self.label = QtWidgets.QLabel(self.window)
        self.label.setGeometry(QtCore.QRect(280, 70, 571, 71))
        self.label.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label.setStyleSheet("font: 26pt \"Segoe UI\"; color: rgb(255, 255, 255)")
        self.label.setAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignTop)
        self.label.setObjectName("label")
        self.pushButton_2 = QtWidgets.QPushButton(self.window)
        self.pushButton_2.setGeometry(QtCore.QRect(500, 370, 121, 31))
        self.pushButton_2.setStyleSheet("color: rgb(74, 113, 255);\n"
"font: italic 9pt \"Segoe UI\";")
        self.pushButton_2.setObjectName("pushButton_2")
        self.label_2 = QtWidgets.QLabel(self.window)
        self.label_2.setGeometry(QtCore.QRect(440, 100, 301, 61))
        self.label_2.setStyleSheet("color: rgb(255, 255, 255);\n"
"font: italic 15pt \"Segoe UI\";")
        self.label_2.setObjectName("label_2")
        self.UsernameHandle = QtWidgets.QLineEdit(self.window)
        self.UsernameHandle.setGeometry(QtCore.QRect(480, 220, 171, 31))
        self.UsernameHandle.setObjectName("UsernameHandle")
        self.label_3 = QtWidgets.QLabel(self.window)
        self.label_3.setGeometry(QtCore.QRect(480, 200, 71, 21))
        self.label_3.setStyleSheet("font: 11pt \"Segoe UI\"; color: rgb(255, 255, 255)")
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.window)
        self.label_4.setGeometry(QtCore.QRect(480, 280, 71, 21))
        self.label_4.setStyleSheet("font: 11pt \"Segoe UI\"; color: rgb(255, 255, 255)")
        self.label_4.setObjectName("label_4")
        self.PasswordHandle = QtWidgets.QLineEdit(self.window)
        self.PasswordHandle.setGeometry(QtCore.QRect(480, 300, 171, 31))
        self.PasswordHandle.setObjectName("PasswordHandle")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 874, 22))
        self.menubar.setObjectName("menubar")
        self.menuHome = QMen(self.menubar)
        self.menuHome.setGeometry(QtCore.QRect(0, 0, 100, 30))
        self.menuHome.setObjectName("menuHome")
        self.menuLogin = QMen(self.menubar)
        self.menuLogin.setGeometry(QtCore.QRect(0, 0, 100, 30))
        self.menuLogin.setObjectName("menuLogin")
        self.menuDashboard = QMen(self.menubar)
        self.menuDashboard.setGeometry(QtCore.QRect(0, 0, 100, 30))
        self.menuDashboard.setObjectName("menuDashboard")
        MainWindow.setMenuBar(self.menubar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setStatusTip(_translate("MainWindow", "Project"))
        self.label.setText(_translate("MainWindow", "Login "))
        self.pushButton_2.setStatusTip(_translate("MainWindow", "Login"))
        self.pushButton_2.setText(_translate("MainWindow", "Login"))
        self.label_2.setText(_translate("MainWindow", "Sign in to your existing account"))
        self.label_3.setText(_translate("MainWindow", "Username"))
        self.label_4.setText(_translate("MainWindow", "Password"))
        self.menuHome.setProperty("title", _translate("MainWindow", "Introduction"))
        self.menuLogin.setProperty("title", _translate("MainWindow", "Sign in"))
        self.menuDashboard.setProperty("title", _translate("MainWindow", "Draft Layout"))
from qmen import QMen


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
